# Network configuration
[network]
    # interface, listen for ssdp and dlna connections
    # "" - mean autodetect
    iface = ""

    # ip addresses on which server listens,
    # "" - mean autodetect and skip "127.0.0.1"
    ip = ""

# Server configuration
[server]
    # port, default is auto detected available port
    port = 55975
    # Header "SERVER:" for ssdp and dlna server
    header = "Macos/15.0 UPnP/1.0 GoDLNA/0.1"

# SSDP configuration
[ssdp]
    # Instead of build-in ssdp server use minissdpd with defined path to socket
    # Optional, default is empty
    minissdpd = "/var/run/minissdpd.sock"
    # Number of seconds the advertisement is valid
    # Optional, default 30 minutes (30m), used with build-in ssdp server, for minissdpd no sence
    max_age = "30m"
    # Interval at which the device re-send advertisements
    # Optional, default is "2/5 * max_age", used with build-in ssdp server, for minissdpd no sence
    notify_interval = "12m"
    # The time-to-live (TTL) of each IP packet for each multicast message
    # Optional, default is 4, used with build-in ssdp server, for minissdpd no sence
    notify_ttl = 4

# Logger configuration
[logger]
    # Optional, (default is info) Possible values: debug, info, warn, error
    level = "debug"

# Device configuration
[device]
    # Optional, Name, as you see it on TV
    friendlyName = "Video"

    # Optional, unique device ID - string, should be string like "uuid:${UUIDv4}"
    # By default build by md5(friendlyName) =>  "uuid:%x-%x-%x-%x-%x"
    uuid = "uuid:da2cc462-0000-0000-0000-44fd2452e0FF"

# Video store configuration
[store]
    # required, directory with media files
    media_dir = "storage/media"
    # required, directory where generated cache files will be stored
    cache_dir = "storage/cache"
    # how often should be checked directory changes
    # optional (default 10 minutes)
    cache_life_time = "10m"

# Used binaries configuration
[programs]
    # optional, the global path to find and execute the `ffprobe` program
    ffprobe = "ffprobe"
    # optional, the global path to find and execute the `ffmpeg` program
    ffmpeg = "ffmpeg"


# https://github.com/BurntSushi/toml/pull/346
#
# Notice about duration configuration:
# - ssdp.max_age, ssdp.notify_interval, store.cache_life_time
#
# A duration must be as "number<unit>", without any spaces. Valid units are:
#
#        ns         nanoseconds (billionth of a second)
#        us, µs     microseconds (millionth of a second)
#        ms         milliseconds (thousands of a second)
#        s          seconds
#        m          minutes
#        h          hours
#
# You can combine multiple units; for example "5m10s" for 5 minutes and 10 seconds.